version: "3"
services:
  web:
    build: .
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./ui/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
